name: Lint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**"
      - "package*.json"
      - "eslint.config.mjs"

jobs:
  lint:
    name: ESLint & Code Style Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: "20.x"
          cache: "npm"
      - name: Install
        run: npm ci
      - name: Lint Codebase
        run: npm run lint
